### ISSUE TITLE
Default 'student' permissions are too liberal

### ISSUE THREAD

**Issue by jeddobson** [PoeticMediaLab/LacunaStories#122]
The default install (from fresh install via Github) gives far too many permissions to the student role.  The following screenshot shows default 'Content Access' permissions for Student (there are many more):

![screen shot 2016-01-25 at 12 31 57 pm](https://cloud.githubusercontent.com/assets/11461294/12558857/d7be989e-c35f-11e5-82f4-5feb96182271.png)

**Comment by mwidner** [comment]
Thanks for the report, Jed. My sites don't show that same permissions. I'll run another fresh install, though, and see if I can duplicate the issue. Just to rule out any possibilities: did you use a new database, too, or was there possibly a pre-existing one? Thanks again.

**Comment by jeddobson** [comment]
Hi,

It was brand new. I dropped the old database, git clone'd, created a new 
db, and installed.

Jed

**Comment by mwidner** [comment]
Yup. I confirmed this. I'm pretty sure we don't even use Content Access anymore, but I need to run a setup without and verify that everything still works.

**Comment by mwidner** [comment]
Note: I found several more problems with student permissions. Not sure how those got added!

**Comment by mwidner** [comment]
Fixed in develop branch.
