### ISSUE TITLE
Default 'materials' view not given to student role

### ISSUE THREAD

**Issue by jeddobson** [PoeticMediaLab/LacunaStories#123]
From a fresh install, the default settings for the 'materials' view restricts access to the student role. Access to the student role should be given by default to this (and maybe other views?). Screenshot included below shows default settings:

![screen shot 2016-01-25 at 12 35 45 pm](https://cloud.githubusercontent.com/assets/11461294/12558961/68bf403c-c360-11e5-9bb9-b8a48f6624f8.png)

**Comment by mwidner** [comment]
Thanks for the report. I'll look into this one as well. Could possibly be a recent regression! Which branch did you pull from?

**Comment by jeddobson** [comment]
Hi,


[root@vagus LacunaStories]# git branch
* master

Thanks!

Jed

**Comment by mwidner** [comment]
Confirmed. Not sure how this one crept in there!

**Comment by mwidner** [comment]
Fixed in the develop branch.
