### ISSUE TITLE
Can't see Stitchings in single Thread view - permissions issue?

### ISSUE THREAD

**Issue by linkalis** [PoeticMediaLab/LacunaStories#145]
On our installation of Lacuna Stories, when an instructor or student creates a Thread and adds Stitchings to it, they aren't able to see the table full of Stitchings in the single thread view (/thread/sample-thread).  They can see everything else on the page, just not the Stitchings table within it. 

From the Threads list view (/threads), students and instructors _are_ able to see a count of the number of Stitchings that _should_ be visible--they just can't actually view these Stitchings when they click into the specific Thread.

Site admins, on the other hand, don't seem to have a problem seeing this Stitchings table.

**Comment by mwidner** [comment]
Thanks for the report. This is because you're on the 'develop' branch and there are some in-progress changes going on to that part of the code. I'll let you know once they're fixed, which should be sometime next week.

**Comment by mwidner** [comment]
@linkalis I think this was related to the general brokenness of the Sewing Kit / Threads in the current develop branch. It should be fixed now!
