### ISSUE TITLE
LacunaStories - Update to Drupal 7.5.1

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#168]
Hi

I am running LacunaStories  on a Ubuntu 16.04 virtual host with Drupal core 7.5.0
The Status Report in LacunaStories says that 7.5.1 is available, but requires a manual upgrade.
Has anyone done this? Will LacunaStories work on Drupal 7.5.1. 
I have already backed up the entire DB (Backup & Migrate).
Can someone please walk me thru the upgrade procedure? Hopefully it's not too tedious (steps).
Thank you

**Comment by mwidner** [comment]
Lacuna should work just fine with Drupal 7.5.1, so long as you're careful not to update the d3 module, too. Usually, updates pick up everything, including contributed modules. Here are the canonical directions for updating:

https://www.drupal.org/node/250790

The simplest route is to use drush via the `drush up` command. Just don't update the d3 module, as I mentioned.
