### ISSUE TITLE
LacunaStories site down - nothing rendering when accessing url (blank page)

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#199]
Please help!!! My lacunastories site will not come online. Running on virtual ubuntu 16.04 server.

This is what I see in /var/log/apache2/error.log (see attached
<img width="656" alt="screenshot 2017-02-07 22 31 59" src="https://cloud.githubusercontent.com/assets/12171475/22722593/44c7f5e2-ed86-11e6-98be-962a4174a308.png">

**Comment by pguerr061703** [comment]
Somehow it looks like i'm at php version 7.1 
<img width="606" alt="screenshot 2017-02-07 22 48 02" src="https://cloud.githubusercontent.com/assets/12171475/22722816/822c5e68-ed87-11e6-87ac-2e5efc824703.png">
 Not sure how the upgrade took place, but it caused my site to fail

**Comment by mwidner** [comment]
Looks a server configuration issue. Here's a thread that discusses it: 

https://www.drupal.org/node/1016622

Sounds like the upgrade leaves you missing a system library: php7.0-mysql

So, probably `sudo apt-get install php7.0-mysql` would fix it.
