### ISSUE TITLE
Register and login site not found after enabling SSL redirect

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#204]
after enabling SSL (http-->https), the links are not working for my lacunastories site.
http://lacunatest.[my domain name]  to  https://lacunatest.[my domain name]  (SSL done on Netscalar)

The site comes up fine, but when i click on links, like "Register" or "Login", they are not found
It says /user/login  NOT FOUND

Any ideas on how to fix this?  
![image](https://cloud.githubusercontent.com/assets/12171475/24112539/3f0942dc-0d70-11e7-84c9-5287ee29b6bc.png)

Lacuna site
![image](https://cloud.githubusercontent.com/assets/12171475/24112722/ddf10e20-0d70-11e7-86e5-389ac384bb4c.png)

**Comment by mwidner** [comment]
Do any other links work? Do you see any relevant error messages in the webserver logs? It sounds like it could be an Apache configuration issue, but I don't have enough information to say for sure.

**Comment by pguerr061703** [comment]
None of the links work on the page. I think it could be Apache configuration, but I don't know where to look, (possiby default-ssl.conf in /etc/apache2/sites-enabled ??

I am still learning Apache, but I sense may I need the following, however that is in my 000-default.conf file  and NOT my default-ssl.conf  (should it be in both)? I am listening on port 443 on server 


       <Directory "/var/www/html">
             Options Indexes FollowSymLinks MultiViews
             AllowOverride All
             Order allow,deny
             allow from all

**Comment by mwidner** [comment]
Ok, sounds like the clean URLs may not be configured to work in Apache when under SSL. Here are the instructions for setting that up:

https://www.drupal.org/https-information

Basically, whatever your original Apache settings were should be the same for the encrypted version of the site. Then, things should work correctly.

**Comment by pguerr061703** [comment]
Got it working...but it comes the issue where I don't remember the administrator account and everytime I go to Lacuna site with my regular Lacuna account, (i.e to do almost anything...i.e enable clean urls..etc) its says "Access Denied"

Is there a way to change the privileges of a user account without going thru the interface (thru Linux commands (ubuntu 16) ?
![image](https://cloud.githubusercontent.com/assets/12171475/24122275/93b28e44-0d91-11e7-9167-ff4902b1dfd5.png)

**Comment by pguerr061703** [comment]
thnks. but I want to change the privilege(Super admin) of the account ... not necessarily the password.

**Comment by mwidner** [comment]
Well, drush is the way to do that, too! :)

**Comment by pguerr061703** [comment]
You are correct:-)  Thank you for you help, You are the best.  I was able to find that command.

drush user-add-role "Site Administrator" <lacuna account name>
