### ISSUE TITLE
LacunaStories on Drupal 8

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#207]
Can Lacunastories work on Drupal 8 ?  How would I go about it ? Any drawbacks or major concerns ?
I have a live production site of Lacunastories on Drupal 7 running on Ubuntu 16.04

**Comment by mwidner** [comment]
Currently, Lacuna is Drupal 7 only. We make use of *many* contributed modules, some of which are not yet ready for Drupal 8. Given that D7 is still supported and receives security updates, there's no reason yet to migrate. We intend to make that migration when D9 comes out and D7 is no longer officially supported.
