### ISSUE TITLE
LacunaStories and LDAP authentication

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#210]
Hi,
Can someone please let me know if there is a way to integrate LDAP authentication into my virtual Ubuntu 16 host running LacunaStories (Drupal 7 currently on this host). If so, how can I get this working? I want registered users in LacunaStories to authenticate their access via LDAP.  I also want to remove the registration link (if possible) from the Home Page of my Lacunastories site. Our university is trying to make the site more secure.  Thank you for any information you can provide.

**Comment by mwidner** [comment]
Hi @pguerr061703. That sounds like an interesting modification. There is a Drupal 7 module for LDAP authentication (https://www.drupal.org/project/ldap). I suspect it would be as simple as installing and configuring that module, then removing the registration link from the main menu.  That said, I have no experience with LDAP and Drupal, but it looks like a stable, well-supported module. Would love to hear about your results trying it.
