### ISSUE TITLE
LDAP authentication in LacunaStories

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#214]
I am running LacunaStories on a virtual host running Ubuntu 16.04. If I'm not mistaken, the drupal version is 7. Can someone inform me if there is a way to have user accounts created in LacunaStories authenticate thru LDAP? We want to secure the site and security team is suggesting LDAP authentication.

Any help to get this working would be greatly appreciated

**Comment by mwidner** [comment]
Sure, you should be able to add the LDAP module (https://www.drupal.org/project/ldap) and configure it. That should make it work.

**Comment by pguerr061703** [comment]
LacunaStories is running on Drupal 7.  This LDAP module requirement is Drupal8. Can you please confirm, or maybe I am missing something. Is there a release of this LDAP module for Drupal 7?

**Comment by mwidner** [comment]
Here's the version for Drupal 7: https://www.drupal.org/project/ldap/releases/7.x-2.3

**Comment by pguerr061703** [comment]
Thank you so much, sir. Much appreciated.

**Comment by pguerr061703** [comment]
I installed the LDAP module on my virtual host, via drush command. Not sure I know where to configure LDAP in LacunaStories though. Is there a config file or something to reference?


[root@myserver] #  drush en ldap*
The following extensions will be enabled: ldap_authentication, ldap_authorization, ldap_authorization_drupal_role, ldap_authorization_og, ldap_feeds, ldap_help, ldap_query, ldap_servers, ldap_test, ldap_user, ldap_views, job_scheduler, feeds
Do you really want to continue? (y/n): y
ldap_user was enabled successfully.                                                                                       [ok]
job_scheduler was enabled successfully.                                                                                   [ok]
ldap_authentication was enabled successfully.                                                                             [ok]
ldap_authorization was enabled successfully.                                                                              [ok]
ldap_authorization_drupal_role was enabled successfully.                                                                  [ok]
ldap_authorization_og was enabled successfully.                                                                           [ok]
ldap_feeds was enabled successfully.                                                                                      [ok]
ldap_help was enabled successfully.                                                                                       [ok]
ldap_query was enabled successfully.                                                                                      [ok]
ldap_servers was enabled successfully.                                                                                    [ok]
ldap_test was enabled successfully.                                                                                       [ok]
ldap_views was enabled successfully.                                                                                      [ok]
feeds was enabled successfully.                                                                                           [ok]

**Comment by mwidner** [comment]
I'm not really sure. Because this is a module not included in the default Lacuna profile, I've never had to configure it. I can suggest that you refer to the LDAP module documentation. It should explain how to configure it.
