### ISSUE TITLE
Version of LacunaStories

### ISSUE THREAD

**Issue by pguerr061703** [PoeticMediaLab/LacunaStories#221]
Hello.  I installed Lacunastories about two years ago on a Ubuntu server, but don't remember the version of LacunaStories. We have been doing updates to drupal..etc..

Is there way to determine the original bundled version of Lacunastories that I used ? Possibly a file?
I cannot recall.

Thank you

**Comment by dabush** [comment]
Hi,
If you have updated to the newest version the version number should be at
the top of the status report (under Configuration).


Daniel
