### ISSUE TITLE
Moodle LTI consumer cannot show up the "Manage Lacuna" menu item

### ISSUE THREAD

**Issue by fishfree** [PoeticMediaLab/LacunaStories#240]
In moodle, I follow the Canvas integration instructions [here](https://github.com/PoeticMediaLab/Lacuna#add-lacuna-as-a-canvas-app).  All works except the "Manage Lacuna" menu item, there is no such menu item in Moodle.

**Comment by mwidner** [comment]
The integration has only been tested with Canvas, not Moodle. I strongly suspect there's a different setup required in Moodle to make things show up in the menu than there is in Canvas.

**Comment by fishfree** [comment]
@mwidner This is the screenshot of the Moodle LTI config page. I cannot figure out which fields can provide the "Manage Lacuna" menu functionality.
![image](https://user-images.githubusercontent.com/1741341/57742281-1a301500-76f3-11e9-98f4-358ebc5eaac9.png)

**Comment by mwidner** [comment]
Lacuna does not provide automatic configuration support for Moodle like it does for Canvas.

**Comment by fishfree** [comment]
@mwidner I just paste the ***/lti/canvas.xml in Moodle, Moodle automatically parsed it and populated the configuration forms. Now I guess it is because Moodle doe not support the lticm:options as a LTI consumer.

**Comment by mwidner** [comment]
Oh, that would make sense.
