### ISSUE TITLE
expired certificate for lacunastories.com

### ISSUE THREAD

**Issue by jeddobson** [PoeticMediaLab/LacunaStories#242]
The SSL certificate has expired for www.lacaunastories.com.

**Comment by mwidner** [comment]
Oops! Thanks for letting us know!

**Comment by ak00001** [comment]
I can't reach www.lacunastories.com

**Comment by ak00001** [comment]
I still experience an expired certificate for www.lacunastories.com

**Comment by mwidnerCRM** [comment]
I cannot replicate that. Try clearing your browser cache and make sure you're visiting https://www.lacunastories.com
